server.port=8085

#With in-memory database
#spring.datasource.url=jdbc:h2:mem:academic-db;DATABASE_TO_UPPER=FALSE
#spring.h2.console.enabled=true
#spring.jpa.open-in-view=false

#With mysql-db
#spring.datasource.url=jdbc:mysql://localhost:3306/academics
#spring.datasource.username=admin
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver