#Fichier : config-repo/user-service-dev.properties

#En dev, on veut que la base de données soit recréée à chaque fois
#et que nos scripts SQL soient exécutés.
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always
#spring.sql.init.platform=h2

#On peut aussi activer des logs plus verbeux en dev
#logging.level.com.project.user_service=DEBUG

#Nouvelle configuration pour le dev avec MySQL info de la bd dans le fichier .env.propertiesde user-service
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
#spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${MYSQL_DB_USER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.project.academic_service=DEBUG
