-- src/main/resources/schema.sql

-- Drop table if exists to ensure a clean start
DROP TABLE IF EXISTS registration;
-- Création de la table registration
-- La table n'a pas de contrainte de clé étrangère vers student
CREATE TABLE registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number BIGINT NOT NULL UNIQUE,
    level VARCHAR(255),
    date_of_registration TIMESTAMP,
    matricule VARCHAR(255) NOT NULL
);

-- Création de la table student (simulation du user-service)
-- Note : L'id doit être de type BIGINT car Long en Java correspond à un BIGINT en SQL

--CREATE TABLE student (
--    id BIGINT PRIMARY KEY,
--    matricule VARCHAR(255) NOT NULL UNIQUE,
--    first_name VARCHAR(255),
--    last_name VARCHAR(255),
--    email VARCHAR(255),
--    address VARCHAR(255),
--    telephone VARCHAR(255),
--    birthday DATE,
--    gender VARCHAR(255)
--);