-- src/main/resources/schema.sql

-- Drop table if exists to ensure a clean start
DROP TABLE IF EXISTS registration;
-- Création de la table registration
-- La table n'a pas de contrainte de clé étrangère vers student

CREATE TABLE IF NOT EXISTS registration (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    registration_number BIGINT NOT NULL UNIQUE,
    level VARCHAR(255),
    date_of_registration TIMESTAMP,
    matricule VARCHAR(255) NOT NULL,
    academic_year_label VARCHAR(255) NOT NULL,
    speciality_label VARCHAR(255) NOT NULL
);
ALTER TABLE registration MODIFY registration_number BIGINT NOT NULL DEFAULT 0;

--CREATE SEQUENCE IF NOT EXISTS registration_number_seq START WITH 1 INCREMENT BY 1;

--CREATE TABLE IF NOT EXISTS registration_number_seq (
--    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
--);
--
--INSERT INTO registration_number_seq VALUES (NULL);
--SELECT LAST_INSERT_ID();