#version: '3.8'
services:
  jenkins:
    #image: jenkins/jenkins:lts-jdk17 # Image officielle de Jenkins avec le JDK 17
    build: .
    container_name: jenkins-ensitech
    privileged: true # Donne des permissions étendues
    user: root # Pour éviter les problèmes de permissions au début
    ports:
      - "9090:8080" # On accède à Jenkins via localhost:9090
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home # Stocke les données de Jenkins pour qu'elles persistent
      - /var/run/docker.sock:/var/run/docker.sock # Permet à Jenkins de lancer des commandes Docker (avancé)

  discovery-service:
      build: ./discovery-service
      container_name: discovery-service-container
      ports:
       - 8761:8761

  config-service:
    build: ./config-service
    container_name: config-service-container
    ports:
      - 9999:9999
    #depends_on:
      #- discovery-service

  academic-service:
    build: ./academic-service
    container_name: academic-service-container
    ports:
      - 8085:8085

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service-container
    ports:
      - 8083:8083

  registration-service:
    build: ./registration-service
    container_name: registration-service-container
    ports:
      - 8086:8086

  training-service:
    build: ./training-service
    container_name: training-service-container
    ports:
      - 8084:8084

  user-service:
    build: ./user-service
    container_name: user-service-container
    ports:
      - 8081:8081

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service-container
    ports:
      - 8888:8888

volumes:
  jenkins_data: